language: node_js
node_js:
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: mc.s.pain.how.er+npm@gmail.com
  api_key:
    secure: "W2+uMw1lHh16tQ8HiAgU5g1BKiS3PHzlWvGX92R4AEYpnIiMyAk9C9JEx4mZH4Br8WY3p+R23dy1LX2jugY2lw+qqblNAlymaX1GBwvBdITZpx29WtUlRuz2KojMLmiCJ8Kz4gSx8DFuIXCMSRKvkKOMtOF/W4qIDM4wBQzlCPcwLBTm41qRKv0msZKOQSO6uCD+xXOFaiqbBDzF7uzHCQgLFmM9gjWBJ1IXodvmZ2HGSmNyooEwc9X6QzhNnEsQ+qyD/vbGFjoAzED9pk9LHLr7DVu/P7sTrKU3jHMZSH5oX3WF4OX/Z/i1MzNaNon2liRCDmq9YBawd5he3S51voRgBDTeWeG6VJ+fpOkuYKmZ0aFyl4WUQ6XqRYi41L/cKldRi2EgEJVZpw14p3qm870Au9zriKJ1xnNYDiLj2l17dIvrb5n/fKcHcyOXFAVgxh0m/xm75ip3fhFM9gEHtX/Pq1vP/aPfMr43mpsjw0i0mbBLt2mddbxq3y4jk0ArUfA4orsZ8PN+cd3PV+xbXatnGIpI8Du7dQ4ytBfGsCVKm+T6fjkNTdtPjK9W754snGSw2fdOXXXRP4Yx41y9nihTA16YRZbkGF+pTXGrUKRYJgG5zKQuUsoADltsamxVy6px2CYaAVw30ttSaJsBcvSRY4bo2EiVbWRCfuGp64M="
  on:
    node: '0.12'
    tags: true
    all_branches: true
    repo: home-buddy/rest-buddy
